djangoapp/blog/urls.py
from django.urls import path
from .views import index, page, post, created_by, category, tag, search

app_name = 'blog'

urlpatterns = [
    path('', index, name='index'),
    path('post/<slug:slug>', post, name='post'),
    path('page/<slug:slug>', page, name='page'),
    path('created_by/<int:author_pk>', created_by, name='created_by'),
    path('category/<slug:slug>', category, name='category'),
    path('tag/<slug:slug>', tag, name='tag'),
    path('search/', search, name='search'),
]

djangoapp/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('blog.urls'))
]

if settings.DEBUG:
    # precisa ser adicionar para poder ver aquivos adicionados pelo usuario
    # em desenvolvimento
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

djangoapp/blog/models.py
from django.db import models
from utils.rands import slugify_new
from django.contrib.auth.models import User
from utils.images import resize_image
from django_summernote.models import AbstractAttachment
from django.urls import reverse


class PostAttachment(AbstractAttachment):
    def save(self, *args, **kwargs):
        if not self.name:
            self.name = self.file.name

        current_file = str(self.file.name)
        super().save(*args, **kwargs)
        changed = False

        if self.file:
            changed = current_file != self.file

        if changed:
            resize_image(self.file, 900, True, 70)


class Tag(models.Model):
    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

    name = models.CharField(max_length=255)
    slug = models.SlugField(
        unique=True, default=None, null=True,
        blank=True, max_length=255
    )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.name, 5)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=255)
    slug = models.SlugField(
        unique=True, default=None, null=True,
        blank=True, max_length=255
    )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.name, 5)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class PageManager(models.Manager):
    def get_published(self):
        return self\
            .filter(is_published=True) \
            .order_by('-pk')


class Page(models.Model):
    objects = PageManager()
    title = models.CharField(max_length=65)
    slug = models.SlugField(
        unique=True, default='',
        null=False, max_length=255
    )
    is_published = models.BooleanField(
        default=False,
        help_text='indica se o site vai poder ser acessado'
    )
    content = models.TextField()

    def get_absolute_url(self):
        if not self.is_published:
            return reverse('blog:index')
        return reverse('blog:page', args=(self.slug,))

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.title, 5)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class PostManager(models.Manager):
    def get_published(self):
        return self\
            .filter(is_published=True) \
            .order_by('-pk')


class Post(models.Model):
    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    # objects = models.Manager()  # padrao
    objects = PostManager()

    title = models.CharField(max_length=65)
    slug = models.SlugField(
        unique=True, default='',
        null=False, blank=True, max_length=255
    )
    excerpt = models.CharField(max_length=150)
    is_published = models.BooleanField(
        default=False,
        help_text='indica se o post vai poder ser acessado'
    )
    content = models.TextField()
    cover = models.ImageField(
        upload_to='post/%Y/%m/',
        blank=True, default=''
    )
    cover_in_post_content = models.BooleanField(
        default=True,
        help_text="exibe a imagem de capa tambem dentro do post"
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        auto_now=True
    )
    created_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True, null=True,
        related_name='post_created_by'
    )
    updated_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True, null=True,
        related_name='post_updated_by'
    )
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True,
        default=None
    )

    tags = models.ManyToManyField(Tag, blank=True, default='')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        if not self.is_published:
            return reverse('blog:index')
        return reverse('blog:post', args=(self.slug,))

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.title, 5)

        current_cover = str(self.cover.name)

        super().save(*args, **kwargs)

        changed = False

        if self.cover:
            changed = current_cover != self.cover

        if changed:
            resize_image(self.cover, 900, True, 70)

djangoapp/blog/views.py
from django.shortcuts import render

# Create your views here.

djangoapp/blog/views/blog_views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from blog.models import Post, Page, Category, Tag
from django.db.models import Q
from django.http import Http404
from django.contrib.auth.models import User

PER_PAGE = 9


def index(request):
    posts = Post.objects \
        .order_by('-pk') \
        .filter(is_published=True)
    paginator = Paginator(posts, PER_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'site_title': 'Home - ',
        'page_obj': page_obj
    }
    return render(
        request,
        'blog/pages/index.html',
        context
    )


def post(request, slug):
    post = (
        Post.objects.get_published()
        .filter(slug=slug)
        .first()
    )

    if post is None:
        raise Http404()

    post_title = post.title

    context = {
        'site_title': f'Post {post_title} - ',
        'post': post
    }
    return render(
        request,
        'blog/pages/post.html',
        context
    )


def page(request, slug):
    page = (
        Page.objects.get_published()
        .filter(slug=slug)
        .first()
    )

    if page is None:
        raise Http404()

    page_title = page.title

    context = {
        'site_title': f'Page {page_title} - ',
        'page': page
    }
    return render(
        request,
        'blog/pages/page.html',
        context
    )


def created_by(request, author_pk):
    posts = Post.objects.get_published()\
        .filter(created_by__pk=author_pk)

    paginator = Paginator(posts, PER_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    users = User.objects.filter(pk=author_pk).first()

    if users is None:
        raise Http404()

    author_name = users.username

    if users.first_name and users.last_name:
        author_name = f'{users.first_name} {users.last_name}'

    context = {
        'site_title': f'Author {author_name} - ',
        'page_obj': page_obj
    }
    return render(
        request,
        'blog/pages/index.html',
        context
    )


def category(request, slug):
    posts = Post.objects.get_published()\
        .filter(category__slug=slug)
    paginator = Paginator(posts, PER_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    categories = Category.objects.filter(slug=slug).first()

    if categories is None:
        raise Http404()

    category_name = categories.name

    context = {
        'site_title': f'Category {category_name} - ',
        'page_obj': page_obj
    }
    return render(
        request,
        'blog/pages/index.html',
        context
    )


def tag(request, slug):
    posts = Post.objects.get_published()\
        .filter(tags__slug=slug)
    paginator = Paginator(posts, PER_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    tags = Tag.objects.filter(slug=slug).first()

    if tags is None:
        raise Http404()

    tag_name = tags.name

    context = {
        'site_title': f'Tag {tag_name} - ',
        'page_obj': page_obj
    }
    return render(
        request,
        'blog/pages/index.html',
        context
    )


def search(request):
    search_value = request.GET.get('q', '').strip()
    posts = (
        Post.objects.get_published()
        .filter(
            # titulo contem search_value ou
            # excerpt contem search_value ou
            # conteudo contem search_value
            Q(title__icontains=search_value) |
            Q(excerpt__icontains=search_value) |
            Q(content__icontains=search_value)
        )[0:PER_PAGE]
    )

    context = {
        'site_title': f'Search {search_value} - ',
        'page_obj': posts,
        'search_value': search_value
    }
    return render(
        request,
        'blog/pages/index.html',
        context
    )

djangoapp/blog/templates/blog/pages/index.html
{% extends 'blog/base.html' %}

{% block content %}
  <main class="main-content section-wrapper">
    <div class="section-content-wide">
      <div class="section-gap">
        {% if page_obj %}
          <div class="card-grid">
            {% for post in page_obj %}
              {% include 'blog/partials/_post-card.html' %}
              {% comment %} with i=forloop.counter0 {% endcomment %}
            {% endfor %}
          </div>
        {% else %}
          {% include 'blog/partials/_not-found.html' %}
        {% endif %}
      </div>
    </div>
  </main>
{% endblock content %}

djangoapp/blog/templates/blog/pages/page.html
{% extends 'blog/base.html' %}

{% block content %}
  <main class="main-content section-wrapper">
    <div class="section-content-narrow">
      <div class="section-gap">
        <h1 class="center">{{ page.title }}</h1>
        {{ page.content | safe }}
      </div>
    </div>
  </main>
{% endblock content %}

djangoapp/blog/templates/blog/pages/post.html
{% extends 'blog/base.html' %} 

{% block additional_head %}
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/codemirror.min.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/theme/dracula.min.css">

  <script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/codemirror.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/python/python.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/javascript/javascript.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/htmlmixed/htmlmixed.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/css/css.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/xml/xml.min.js"></script>
{% endblock additional_head %}

{% block content %}
  {% if post %}
    <main class="main-content single-post section-wrapper">
      <div class="single-post-content section-content-narrow">
        <div class="single-post-gap section-gap">
    
          {% if post.cover and post.cover_in_post_content %}
            <div class="single-post-cover pb-base">
              <img loading="lazy" src="{{ post.cover.url }}" alt="Cover da capa do post {{ post.title }}">
            </div>
          {% endif %}
    
          <h2 class="single-post-title pb-base center">
            {{ post.title }}
          </h2>
    
          <div class="post-meta pb-base">
            <div class="post-meta-item">
              <a class="post-meta-link" href="{% url 'blog:created_by' post.created_by.pk %}">
                <i class="fa-solid fa-user"></i>
                <span>
                  {% if post.created_by.first_name and post.created_by.last_name %}
                    {{ post.created_by.first_name }} {{ post.created_by.last_name }}
                  {% else %}
                    {{ post.created_by.username }}
                  {% endif %}
                </span>
              </a>
            </div>
            <div class="post-meta-item">
              <span class="post-meta-link">
                <i class="fa-solid fa-calendar-days"></i>
                <span>
                  {{ post.created_at }}
                  {% comment %}
                    formatar data:
                    https://docs.djangoproject.com/en/4.2/ref/templates/builtins/#date
                    {{ post.created_at | date: "d/m/Y \à\s H:i" }}
                  {% endcomment %}
                </span>
              </span>
            </div>

            {% if post.category %}
            <div class="post-meta-item">
              <a class="post-meta-link" href="{% url 'blog:category' post.category.slug %}">
                <i class="fa-solid fa-tag"></i>
                <span>
                  {{ post.category }}
                </span>
              </a>
            </div>
            {% endif %}

          </div>
          <p class="single-post-excerpt pb-base">
            {{ post.excerpt | safe }}
          </p>
    
          <div class="separator"></div>
    
          <div class="single-post-content">
            {% comment %} {% include 'blog/partials/_temp.html' %}  {% endcomment %}

            {{ post.content | safe }}
          
            <div class="post-tags">
              <span>Tags: </span>
              
              {% comment %} tags é uma relação many to many {% endcomment %}
              {% if post.tags.exists %}
                {% for tag in post.tags.all %}
                  <a class="post-tag-link" href="{% url 'blog:tag' tag.slug %}">
                    <i class="fa-solid fa-link"></i>
                    <span>{{ tag.name }}</span>
                  </a>
                {% endfor %}
              {% endif %}

            </div>
            
          </div>
        
        </div>
      </div>
    </main>
  {% else %}
    {% include 'blog/partials/_not-found.html' %}
  {% endif %}
{% endblock content %}